### ISSUE TITLE
Merge RR directly into crossbeam?

### ISSUE THREAD

**Issue by gatoWololo** [gatoWololo/rr_channel#10]
@asajeffrey 
The current implementation works. It could definitely use some refactoring and cleaning up! However I'm holding off since it seems like what we really want is to implement RR directly into crossbeam.

The current implementation wraps `crossbeam_channel::select!` as well as `Receiver` and `Sender` by creating `rr_channel::*`, equivalents. If the eventual goal is to integrate with Servo. It seems changing the types of everything to use `rr_channel` in Servo would be more work.

It would be pretty straightforward to fork `crossbeam_channel` and modify Receiver and Sender to work with our code. No macro changes needed! The `Select` changes seem harder. The implementation seems to try to do a few fancy things, so careful changes need to be made to ensure we don't break the semantics.

Then using RR in Servo would be as simple as changing their crossbeam version for ours?
Thoughts?

**Comment by asajeffrey** [comment]
Ideally, `rr_channel` would be a wrapper around `crossbeam_channel`, but that's made tricky by the `select!` macro requiring crossbeam channels, not wrapped versions (e.g. https://docs.rs/crossbeam-channel/0.3.8/src/crossbeam_channel/select_macro.rs.html#630).

If we copy `select_macro.rs` from `crossbeam_channel` then it's binding for `$crate` will be `rr_channel` rather than `crossbeam_channel` which might be enough for us to do our monkey patching?

We coouuuuuuld fork `crossbeam_channel` and put the changes in the fork, but that presents all the usual problem of maintaining forks.

**Comment by gatoWololo** [comment]
> all the usual problem of maintaining forks.

Right.

I see. We would basically copy their APIs as well to make things like `let mut _sel = $crate::Select::new();` or `let _oper: $crate::SelectedOperation<'_>` work. Okay, besides abusing their macros to avoid wrapping `Select` that's _roughly_ what I have been doing. So it's not too hard to continue extending.

When we want to integrate those changes into servo would we just `sed s/crossbeam_channel/rr_channel/` :b for all [instances](https://github.com/servo/servo/search?l=Rust&p=3&q=crossbeam_channel) in servo?

**Comment by asajeffrey** [comment]
To integrate this with Servo, we'd probably add a new feature, which would swap between channel providers.

**Comment by asajeffrey** [comment]
Might also be worth abusing https://doc.rust-lang.org/1.1.0/std/macro.include!.html to include the defn of crossbeam's select textually.

**Comment by gatoWololo** [comment]
Great! The latest commit on devel fa6df75176a216214df40a907fb25ede7112d71c implements the wrappers. We no longer need to hook into any macro ugliness as the native select! macro _just works_ with our `rr_channel` wrappers. Some cleaning up is necessary before merging. But it works compiles, and runs on `example/many_threads.rs` other examples need to be converted over (which is super easy)
