### ISSUE TITLE
Examples with random delay?

### ISSUE THREAD

**Issue by asajeffrey** [gatoWololo/rr_channel#11]
To introduce more nondeterminism, can we put random delay into the sending loop?

**Comment by gatoWololo** [comment]
We now have [/examples/multiple_producers_random_delays.rs](https://github.com/gatoWololo/rr_channel/blob/devel/examples/multiple_producers_random_delays.rs).

All examples could benefit from being extra nondeterministic, thus stress testing our implementation. I wonder if they should all be modified?

**Comment by gatoWololo** [comment]
Plenty of examples now have random delays. Specially the `try_recv()` and `recv_timeout()` examples.
