### ISSUE TITLE
Buffering Receive Messages

### ISSUE THREAD

**Issue by gatoWololo** [gatoWololo/rr_channel#7]
@asajeffrey One thing that is not obvious to me: How exactly do we buffer the receive messages on the multiple producer scenario.

I see a few general solutions:
- Global data: We cannot have a global data structure since what would be the type of the elements? We need to be able to hold `T`s for any type of channel data.
- Per Select: For any given select, all the data is homogeneous. From the macro, even if I don't have the explicit type, I think I can type inference `Buffer<_>`. This would require something like C static variables in functions?
- Transmute: Transmute all our data into a generic type. I'm not convinced this is safe.

Any thoughts would be appreciated.

Omar.

**Comment by asajeffrey** [comment]
Write a wrapper type:
```rust
struct Sender<T>(crossbeam_channel::Sender<(ThreadId, T)>);
struct Receiver<T>(Vec<T>, crossbeam_channel::Receiver<(ThreadId, T)>);
```
then implement `send`, `recv` etc for those types so they can be used as drop-in replacements.

**Comment by gatoWololo** [comment]
I see. That makes sense.
