### ISSUE TITLE
Variant of multiple_producers.rs that doesn't use select?

### ISSUE THREAD

**Issue by asajeffrey** [gatoWololo/rr_channel#9]
There should be a variant of multiple_producers.rs that doesn't use select, but is nondeterministic due to the order that messages end up getting interleaved?

**Comment by gatoWololo** [comment]
We now have [examples/multiple_producers_no_select.rs](https://github.com/gatoWololo/rr_channel/blob/devel/examples/multiple_producers_no_select.rs)
